zylon-ai/private-gpt

requirements.txt

pin pygptj

---

requirements.txt

Bumped versions in requirements.txt, tested OK.
langchain 0.0.166 release: https://github.com/hwchase17/langchain/releases/tag/v0.0.166
llama 0.1.48 release: https://github.com/abetlen/llama-cpp-python/releases/tag/v0.1.48

Update langchain and llama versions

---

ingest.py
privateGPT.py

The previous commit introduced .env but it's not being loaded

Load .env file

---

README.md

Update `README` to add instruction notice for reported issue #63 (which is not really an issue, but a `langchain` flaw)

Note on instructions for .env

---

requirements.txt

- Add `python-dotenv` to requirements file
- Address issues related to #133

Add python-dotenv to requirements

---

README.md
ingest.py
requirements.txt

This adds more document loaders and makes it easy to add more.

More loaders, generic method

---

ingest.py

Original code was written by [GuySarkinsky](https://github.com/GuySarkinsky) in issue #448

fixed the the csv file reading issue

---

README.md

Clarified to create a copy of example.env instead of renaming it to prevent accidentally removing from repo

Update README.md instructions of .env file

---

privateGPT.py

Directly press ENTER or search space will get a meaningless result.

Skip for empty query

---

private_gpt/ui/ui.py

So it is easy to know the mode being used: 
"local", "open_ai", "sagemaker", "mock"

Add LLM mode to UI

---

README.md

fix: make docs more visible

---

private_gpt/ui/ui.py

Remove sources from chat history to avoid confusing the LLM
Fixes https://github.com/imartinez/privateGPT/issues/1189

Curate sources to avoid the UI crashing

---

private_gpt/server/ingest/ingest_service.py

So far PrivateGPT has been creating one index per ingested file. 
That makes it difficult to load the index from disk to perform update or delete operations, and it was causing errors during deletion. 
We now reuse the existing index if any. That way we ensure a single index for all files ingested, making it easier to operate with it.

Reuse existing stored index during ingestion

---

private_gpt/server/ingest/ingest_service.py

Fixes https://github.com/imartinez/privateGPT/issues/1227

fix: Windows 11 tmp file permission

---

fern/docs/pages/manual/ingestion.mdx
settings-mock.yaml

Adding some extra docs about embedding settings + adding the embedding.mode: local to the mock profile

Embedding config + docs 

---

fern/docs/pages/recipes/list-llm.mdx

Adding working combination of Large LLM (70B) and Embedding Model to recipe list.
**LLM**:
llm_hf_repo_id: TheBloke/GodziLLa2-70B-GGUF
llm_hf_model_file: godzilla2-70b.Q4_K_M.gguf
HF link: https://huggingface.co/TheBloke/GodziLLa2-70B-GGUF
**Embedding Model**: 
model name: bge-large-en
HF link: https://huggingface.co/BAAI/bge-large-en
Have tested using the GGUF model files available on HF.
Details of my setup-
OS: Ubuntu 20.04
GPU details:
NVIDIA-SMI 545.23.08
Driver Version: 545.23.08
CUDA Version: 12.3
GPU Name: Tesla V100-PCIE-16GB x 4

Adding working combination of LLM and Embedding Model to recipes

---

fern/docs/pages/manual/ingestion.mdx
private_gpt/components/ingest/ingest_component.py
private_gpt/server/ingest/ingest_service.py
private_gpt/settings/settings.py
settings.yaml

Also updated the documentation to show how to configure the ingest mode.

Fix the parallel ingestion mode, and make it available through conf

---

fern/docs/pages/recipes/list-llm.mdx

The best german speaking model I have found so far.

Adding german speaking model to documentation

---

README.md
fern/docs.yml

docs: fix minor capitalization typo

---

fern/docs/pages/manual/llms.mdx
private_gpt/components/llm/llm_component.py
private_gpt/settings/settings.py
settings.yaml

Add support for Ollama LLM

---

private_gpt/ui/ui.py

…m deltas.  This recursive function fires off so quickly to eats up too much of the CPU.  This small sleep frees up the CPU to not be bottlenecked.  This value can go lower/shorter.  But 0.02 or 0.025 seems to work well.
**Here you can view the slow down before the modifications (sorry for the poor quality):**
**And here you can view the speed up after:**
The entire process before this small change, the chat stream took 60-120 seconds or so.
**However after the change it takes about 8-10 seconds for me.**

Updated ui.py to include a small sleep timer

---

settings.yaml

Fixes https://github.com/imartinez/privateGPT/issues/1695

Set default tokenizer to avoid running make setup fail

---

scripts/setup

chore: Update setup

---

private_gpt/ui/ui.py

replaced concat of strings to avoid potential mismatch of types and make code more clear

replaced concat of strings

---

fern/docs/pages/installation/installation.mdx

Added instructions for starting the GPU from AMD.
Tested on AMD RadeonRX 7900 XTX.

Add guide Llama-CPP Linux AMD GPU support

---

private_gpt/components/llm/custom/sagemaker.py

Fix sagemaker implementation not filtering special tokens like `</s>`

fix: special tokens and leading space

---

private_gpt/components/llm/prompt_helper.py
tests/test_prompt_helper.py

Mistral was prompt ignoring assistant messages

fix: mistral ignoring assistant messages

---

fern/docs/pages/overview/welcome.mdx

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

docs: update welcome page

---

private_gpt/ui/ui.py

Zylon text is not showing in light mode

fix: light mode

---

.github/workflows/tests.yml

Required for using Node.js 20.x in CI
* Changelog for actions/checkout@v4 https://github.com/actions/checkout/blob/main/CHANGELOG.md?rgh-link-date=2024-09-04T18%3A38%3A10Z#v400
* GitHub Blog post: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

ci: bump actions/checkout to v4
