zylon-ai/private-gpt

README.md
example.env
ingest.py
privateGPT.py

.env
Added an env file to make configuration easier
LlamaCpp
Added support for LlamaCpp in .env (MODEL_TYPE=LlamaCpp)
PDF/CSV
Added support for PDF and CSV files.
Ingest All
All files in source_documents will automatically get stored in vector store based on their file type when running ingest, no longer need a path argument.

.env + LlamaCpp + PDF/CSV + Ingest All

---

ingest.py

Addressing thread #69 where we noted codebase would ingest only one document from `source_directory`
```python
for root, dirs, files in os.walk("source_documents"):
for file in files:
if file.endswith(".txt"):
loader = TextLoader(os.path.join(root, file), encoding="utf8")
elif file.endswith(".pdf"):
loader = PDFMinerLoader(os.path.join(root, file))
elif file.endswith(".csv"):
loader = CSVLoader(os.path.join(root, file))
documents = loader.load() # loads only the last file content! 
```
@imartinez it would be interesting to think if it is possible to optimize the creation of the `LLAMA` embedding and the `Chroma` db overall. It was already taking quite some time with a single document, and quickly becomes prohibitively slow with more and more docs...

Ingest unlimited number of documents

---

requirements.txt

added library for parsing PDFs

---

ingest.py

Nothing too serious. 'load_dotenv()' in called twice in ingester.py
One line was removed.

remove duplicate call 'load_dotenv()' in ingester.py

---

README.md
ingest.py

To avoid manually converting documents saved in old format, add for the loader to load these as well

Add .doc .ppt (Word and PowerPoint 97/2003 formats)

---

ingest.py

Add fallback for plain elm #294 #290

---

.pre-commit-config.yaml
ingest.py
privateGPT.py

Changes to execute ingest.py and privateGPT.py without needing to manually add python3 for executing them.
Also added a "minimal" pre-commit configuration that will not make major changes to the files - for now it removed some spaces at the end of the lines.  It also checks spelling, yaml format (useful for the docker configuration that is prepared in another PR).

Make scripts executable, add basic pre-commit setup

---

README.md
privateGPT.py

Sometimes may not need the source or the LLM stdout stream to be shown, just need the answer.
Refactored main function to take hide_source and mute_stream parameters for controlling output. 
Added argparse for command-line argument parsing. 
StreamingStdOutCallbackHandler and source document display are now optional based on user input.  
kept the current behaviour as the default when not parsing any arguments. 
Also, updated README.md to reflect these changes.

Added script arguments to disable printing of LLM stdout Stream and source documents

---

ingest.py

Move environment variables to the global scope
Add a better check for vectorstore existence
Introduced a new function for better readability
Co-authored-by: Pulp <51127079+PulpCattel@users.noreply.github.com>
Recreating the PR https://github.com/imartinez/privateGPT/pull/201 due to the history getting way too messy (my frustration was beyond imagination...). Sorry for the inconvenience.

Add script to update the database for adding more documents

---

README.md

On some environments with both Python 2.x and 3.x installed, `pip` will be used for 2.x.

typo: Change `pip` to `pip3` in README.md

---

ingest.py
requirements.txt

The PyMuPDF brings much better performance for PDF loading.
https://pymupdf.readthedocs.io/en/latest/about.html#performance
Here is a comparison article:
https://medium.com/social-impact-analytics/comparing-4-methods-for-pdf-text-extraction-in-python-fd34531034f
It's about **5x-30x faster** for text extraction.
And In my few test cases, PyMuPDF have better result in CJK characters, Although they both may display a lot of garbled characters.
The different is PDFMinerLoader make a single document object but PyMuPDFLoader make each page as a document object.
This PR already contains the change that I've made for this update:
https://github.com/imartinez/privateGPT/pull/560/files
* Remove read subscript [0] only for _loader.load()_
* Update _results.append(doc)_ to  _results.extend(docs)_

Improving performance for PDF loader

---

requirements.txt

gpt4all==0.3.2 was yanked according to https://pypi.org/project/gpt4all/#historyi
Ties to issue 691: https://github.com/imartinez/privateGPT/issues/691

Update gpt4all to 0.3.4

---

privateGPT.py

It's better to raise an exception to handle the error more gracefully than abruptly exiting the script.

raise exception instead of print & exit

---

ingest.py

Files in the source_directory where ignored if their extensions where in uppercase like (*.PDF).
This change supports ingestion of files that match either lowercase or uppercase extensions like *.pdf or *.PDF. 
This can be enhanced further to support camelcase like *.Pdf at a later stage. The assumption is that this scenario is probably less than 5%.

Adding support to ingest files with extensions in uppercase

---

requirements.txt

Adding sentence_transformers to requirements.txt. Two different computers had an issue and pip told me to install this in order to resolve the problem. Fix worked for both computers on python3

Add_sentence_transformers_2.2.2_to_required

---

poetry.lock
private_gpt/components/vector_store/batched_chroma.py
private_gpt/components/vector_store/vector_store_component.py
pyproject.toml
tests/server/ingest/test_ingest_service.py

Take into account, during ingestion, the max batch size allowed by chromadb on a local setup.
Fixes #1084

fix: chromadb max batch size #1084

---

CITATION.cff
LICENSE
README.md

This PR adds a citation file and a license to the repository.
While this info was already available in one form or another, adding it using the standard files not only makes it more accessible, but also allows GitHub to display it more promptly.
I created the citation file with the info I could find, so it's not really complete. You can also add your ORCIDs!
Closes #1006

chore: add GitHub metadata

---

private_gpt/components/embedding/embedding_component.py

At the moment, even if openai is selected as the execution mode, local Embeddings are being used. 
That blocks fully remote setups based on openai, as it uses HuggingFace torch-based embeddings.
With this fix, openai is used both for the LLM and the embeddings when openai is selected in the .yaml llm->model configuration.
Fixes #1093

Use OpenAI for embeddings when openai mode is selected

---

Dockerfile
poetry.lock
private_gpt/settings/yaml.py
pyproject.toml
tests/settings/test_settings_loader.py

https://stackoverflow.com/questions/76327419/valueerror-libcublas-so-0-9-not-found-in-the-system-path

fix: fix pytorch version to avoid wheel bug

---

poetry.lock
private_gpt/__init__.py
private_gpt/__main__.py
private_gpt/components/llm/custom/sagemaker.py
private_gpt/main.py
private_gpt/settings/settings_loader.py
pyproject.toml

* Changed the 2 existing `print` in the `private_gpt` code base into actual python logging, stop using loguru (dependency will be dropped in a later commit).
* Try to use the `key=value` logging convention in logs (to indicate what dynamic values represents, and what is dynamic vs not).
* Using `%s` log style, so that the string formatting is pushed inside the logger, giving the ability to the logger to determine if the string need to be formatted or not (i.e. strings from debug logs might not be formatted if the log level is not debug)
* The (basic) builtin log configuration have been placed in `private_gpt/__init__.py` in order to initialize the logging system even before we start to launch any python code in `private_gpt` package (ensuring we get any initialization log formatted as we …

Drop loguru and use builtin `logging`

---

docs/description.md
scripts/ingest_folder.py

Currently the ingestion progress of an entire folder using the command line script can be quite annoying should errors happen.
Additionally, there is little feedback of the current overall progress if there are many files to be ingested.
For this reason this commit adds two things:
* Wrapping individual documents into a `try except` block
* Improve logging
* Count total documents and show the current document count
* Optionally log to a file
Using the following command as an example:
```bash
poetry run python ./scripts/ingest_folder.py ./tests --log-file ./test.log
```
The new console output can be seen here:
With the following log file being created:

Improve logging and error handling when ingesting an entire folder

---

private_gpt/components/vector_store/vector_store_component.py

When running privateGPT, this was spotted in the logs:
```
chromadb.telemetry.posthog - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
```
One can either disable it in the config object, as done in the PR, or as an env var `ANONYMIZED_TELEMETRY=False`

Disable chromaDB anonymous information collection

---

.github/workflows/docker.yml
Dockerfile.external
Dockerfile.local
poetry.lock
pyproject.toml

We can now execute embeddings locally, there is no need for pytorch or setenence-transformers in the default group
The new docker images are 800MB comapred to the 5GB before.

feat: use different docker image for external execution

---

private_gpt/__init__.py
private_gpt/ui/ui.py

Gradio analytics can be disabled by either using the kwargs `enable_analytics` on `gr.Blocks`, or by setting the env variable `GRADIO_ANALYTICS_ENABLED` to something different from `True`.
Since that Gradio does not seem to respect their code contract (around `enable_analytics`), and that they are performing other operations only based on the value of `GRADIO_ANALYTICS_ENABLED` (c.f. `gradio.strings` https://github.com/gradio-app/gradio/blob/main/gradio/strings.py#L39), we are disabling gradio analytics by setting the required env variable to `False`.
Note: Setting an environment variables using `os.environ['foo'] = 'bar'` on system that are not based on unix might not work.
c.f. https://docs.python.org/3/library/os.html#os.environ for details on how `os.environ` works and all its caveats …

Disable Gradio Analytics

---

private_gpt/__main__.py
private_gpt/components/node_store/node_store_component.py
private_gpt/server/ingest/ingest_router.py
private_gpt/server/ingest/ingest_service.py

A file that is ingested will be transformed into several documents (that are organized into nodes).
This endpoint is deleting documents (bits of a file). These bits can be retrieved thanks to the endpoint to list all the documents.
Also added logs in the scope of this PR

Endpoint to delete documents ingested

---

private_gpt/server/ingest/ingest_service.py

Patch the default list of llama_index to support JSON files. This injection of JSON documents should improve the comprehension in JSON files, as there is a parsing of JSON files.
It **might** avoid the docstore pollution that we've been seeing in reported issues lately

Parse JSON files using llama_index JSONReader

---

.github/workflows/stale.yml

Moving temporarily to 15 days given all PRs and Issues were "updated" on Oct 19 to label them as "primordial"

Stake issues/PRs not update in 15 days

---

private_gpt/main.py
private_gpt/ui/ui.py
scripts/ingest_folder.py

The class `PrivateGptUi` will hold the definition of the UI, as well as it's state.
The `PrivateGptUi` becomes stateless, and the UI will reload the documents that are ingested everytime it needs to (i.e. after a file upload, or every time the UI reloads)
----
Documentation used to change `gradio`'s behaving:
* `DataFrame`: https://www.gradio.app/docs/dataframe
* `UploadButton`: https://www.gradio.app/docs/uploadbutton
* `Blocks`: https://www.gradio.app/docs/blocks
* State in Blocks: https://www.gradio.app/guides/state-in-blocks

Refactor UI state management

---

private_gpt/server/chat/chat_router.py
private_gpt/server/chunks/chunks_router.py
private_gpt/server/completions/completions_router.py
private_gpt/server/embeddings/embeddings_router.py
private_gpt/server/health/health_router.py
private_gpt/server/ingest/ingest_router.py
private_gpt/server/utils/auth.py
private_gpt/settings/settings.py
settings-test.yaml
settings.yaml
tests/fixtures/fast_api_test_client.py
tests/server/ingest/test_ingest_routes.py
tests/server/utils/test_auth.py
tests/server/utils/test_simple_auth.py

To enable the basic authentication, one must set `server.auth.enabled` to true.
The static string defined in `server.auth.secret` must be set in the header `Authorization`.
The health check endpoint will always be accessible, no matter the API auth configuration.
----
The `authenticated` "bean"/"method-in-the-chain" is declared as a dependency in the API router that requires `authenticated` connections. c.f. `faspAPI` documentation for details on `dependencies`: https://fastapi.tiangolo.com/tutorial/bigger-applications/
`Security` section of the fastAPI is also a good read: https://fastapi.tiangolo.com/tutorial/security/

Add simple Basic auth

---

private_gpt/settings/settings.py

We had set it wrong in the Settings Literal, making it impossible to run on openai mode

Fix openai setting literal

---

scripts/setup

enable auto resume download by default to prevent always restart on downloading large file with poor network connection.

feat: enable resume download for hf_hub_download

---

README.md

Using https://shields.io/, and the github action badges: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
To have the complete list of badges available, c.f. to their documentation: https://shields.io/badges
----
Attached, the result of the badges (to effective reviewing - they will be split in two lines: test and doc, and socials)
@imartinez still need to configure the Discord server to remove that "widget disabled" (using the video/tutorial there: https://shields.io/badges/discord)

Add badges in the README.md

---

private_gpt/server/ingest/ingest_service.py

The ingestion API causes some permission troubles over the temporal files on Windows. A fix was recently added here #1260 but the unlinking causes a different trouble. On big files another `PermissionError` is throw because the file still being used by another process.
```
File "E:\PycharmProjects\privateGPT\private_gpt\server\ingest\ingest_service.py", line 124, in ingest
path_to_tmp.unlink()
File "C:\Users\frang\.pyenv\pyenv-win\versions\3.11.0\Lib\pathlib.py", line 1147, in unlink
os.unlink(self)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\frang\\AppData\\Local\\Temp\\tmp4v0e9vnh'
```
Still being a permission error and It dont happen with small files. But closing the file before unlinking the path fix it for …

fix: Windows permission error on ingest service tmp files

---

private_gpt/components/embedding/embedding_component.py
private_gpt/components/ingest/ingest_component.py
private_gpt/components/ingest/ingest_helper.py
private_gpt/components/llm/llm_component.py
private_gpt/server/chunks/chunks_service.py
private_gpt/server/ingest/ingest_router.py
private_gpt/server/ingest/ingest_service.py
private_gpt/server/ingest/model.py
private_gpt/settings/settings.py
private_gpt/ui/ui.py
scripts/ingest_folder.py
settings-ingest-local.yaml
settings.yaml

Multiple strategy for file ingestion.
This is good to be pushed as is.
Following PR will come to add a switch between the implementation using the configuration.
Documentation should be added as well.
Ideally, the most optimal implementation should be debugged as well in this future PR.
---
The current behavior is preserved and will not impact the existing users

Ingestion Speedup Multiple strategy

---

fern/openapi/openapi.json
private_gpt/server/chat/chat_router.py
private_gpt/server/chat/chat_service.py
private_gpt/server/completions/completions_router.py
private_gpt/ui/ui.py
settings.yaml

Allow passing a `system_prompt` in completions API and to send a role:system message in chat/completions APIs messages array to modify the LLM behaviour. 
- Added a basic `system_prompt` to Gradio Query Docs to avoid the LLM answering questions with context that is not in the documents.

Allow passing a system prompt

---

fern/docs/pages/manual/ingestion.mdx

Simple PR adding a note for parametrized `make` calls on Windows. 
Saw that some users were having some troubles making use of it on Windows command line here: #1226 (probably u can close this issue!)
If you prefer a different format to include this note on the docs just let me know and will modify it.
Thanks

Update ingest api docs with Windows support

---

private_gpt/components/llm/llm_component.py
private_gpt/components/llm/prompt_helper.py
private_gpt/settings/settings.py
tests/test_prompt_helper.py

As discussed on Discord, the decision has been made to remove the system prompts by default, to better segregate the API and the UI usages.
A concurrent PR (#1353) is enabling the dynamic setting of a system prompt in the UI.
Therefore, if UI users want to use a custom system prompt, they can specify one directly in the UI. If the API users want to use a custom prompt, they can pass it directly into their messages that they are passing to the API.
In the highlight of the two use case above, it becomes clear that default system_prompt does not need to exist.

feat(llm): drop default_system_prompt

---

fern/docs/pages/manual/llms.mdx
private_gpt/components/llm/llm_component.py
private_gpt/settings/settings.py
settings.yaml

@imartinez This PR allows setting the Open AI model to use in settings as proposed here https://github.com/users/imartinez/projects/3?pane=issue&itemId=44266044. Please feel free to update the board, and let me know if you have any feedback.

Allow setting OpenAI model in settings

---

fern/docs/pages/installation/installation.mdx

I was misled into believing I could install using python 3.12 whereas the pyproject.toml explicitly states otherwise. This PR only removes this comment to make sure other people are not also trapped 😄

docs: remove misleading comment about pgpt working with python 3.12

---

settings.yaml

multiline string in yaml should not be surrounded in quote, instead `>` to condense string as single line or `|` to preserve formating.
https://yaml-multiline.info/
good for a first pull request :muscle:

correct yaml multiline string

---

private_gpt/ui/ui.py

Hi, are you guys open to making the chat area stretch and fill the height of the screen?
This PR addresses #1377 
I have added some CSS to stretch and fill the height of the screen, thanks to @yvrjsharma 's help.
I have tested it using the dev tool. It is responsive and accommodates the recent addition of a system prompt.
https://github.com/imartinez/privateGPT/assets/43847374/f28acde7-9b88-4169-9b90-d758a2c6695e
https://github.com/imartinez/privateGPT/assets/43847374/462398af-8d81-48e6-8500-7870d3e6b477
This will help privateGPT look similar to chatGPT and help with adoption.

feat: made chat area stretch to fill the screen

---

fern/docs/pages/api-reference/api-reference.mdx
fern/docs/pages/overview/welcome.mdx
poetry.lock
pyproject.toml
settings.yaml

- Make TheBloke/Mistral-7B-Instruct-v0.2-GGUF the default model in settings.yaml
- Update LlamaCPP dependency (it now works with modern models, including Mixtral, even though that one requires a 32GB RAM)
- Fix API empty documentation section

Update default model to TheBloke/Mistral-7B-Instruct-v0.2-GGUF

---

fern/openapi/openapi.json
private_gpt/server/ingest/ingest_router.py
private_gpt/server/ingest/ingest_service.py
scripts/ingest_folder.py
tests/fixtures/ingest_helper.py
tests/server/ingest/test_ingest_routes.py

Add a new API to ingest plain text. 
- Deprecate previous /ingest API
- Move previous ingestion logic to a new ingest/file API
- Create a new ingest/text API that allows for plain text ingestion by passing the file_name and the plain text to be ingested. A single Document is generated for the ingested text. 
All the previously existing ingestion logic is reused to leverage the different ingestion capabilities. A little refactor is done in IngestService to accommodate the new text ingestion

Ingest plain text

---

private_gpt/components/llm/llm_component.py
private_gpt/settings/settings.py
scripts/setup
settings.yaml

Extract two key model parameters to settings. 
- Tokenizer: used to calculate the available context window given a prompt in several LlamaIndex pipelines. The default tokenizer is the one used for gpt-3.5 but it is not aligned with, for example, Mistral model. Using huggingface as provider of the tokenizer information, added to setup download script.
- context_window: base model argument

Configurable context_window and tokenizer

---

Dockerfile.external
Dockerfile.local

- Copy scripts folder
- Set the right python paths to use the venv
Instructions:
Build image:
`docker compose build -> builds the image`
Run setup in service to download local models (in case you didn't download them already):
`docker compose run --rm --entrypoint="bash -c '[ -f scripts/setup ] && scripts/setup'" private-gpt`
Run the service:
`docker compose run private-gpt`

Fix dockerfiles

---

fern/docs/pages/manual/llms.mdx
private_gpt/components/llm/llm_component.py
private_gpt/settings/settings.py
settings-vllm.yaml

This mode behaves the same as the openai mode, except that it allows setting custom models not supported by OpenAI. It can be used with any tool that serves models from an OpenAI compatible API.
Note that the mentioned libraries, LocalAI and vLLM, also have their own providers in LlamaIndex. This is a more generic solution that should support those and many more libraries.
One fun implication that I'm testing is the possibility of running PrivateGPT on top of another instance of PrivateGPT. The top-level instance manages embeddings, and the bottom-level instance runs an LLM. With a little additional logic, it could be possible to route requests from the parent instance to multiple child instances based on model id in the request, effectively letting a single PrivateGPT instance serve …

feat(llm): Add openailike llm mode

---

private_gpt/settings/settings_loader.py

Previous implementation causes false positives with the last version of LlamaIndex, making PGPT load settings-test.yaml when being launched. That breaks the UI and other functionalities.

Check for our own test module, given some libs load unittest by default

---

private_gpt/open_ai/openai_models.py

This is a proposed fix for a minor bug I noticed while using [simonw/llm](https://github.com/simonw/llm) to connect to a local privategpt instance -- I'm seeing serialized python error strings in the output. I'm not entirely sure why this shows up in this tool, but not via the UI, but it might have to do with how the output is parsed or something.
Behavior I was seeing:
```llm -m l2-8001 -s "You can only answer questions about the provided context. If you know the answer but it is not based in the provided context, don't provide the answer, just state the answer is not in the context provided." 'what are containers'
Containers, in the context of computing and software development, are lightweight, standalone, executable software packages that include everything needed to run a piece of …
```

Fixing minor bug in chat stream output - python error being serialized

---

fern/docs/pages/recipes/list-llm.mdx
private_gpt/components/llm/prompt_helper.py
private_gpt/settings/settings.py
scripts/extract_openapi.py
settings.yaml
tests/test_prompt_helper.py

this adds what I believe is the correct prompt formatting for Mistral.. based on testing where I've rated it best vs llama-index and llama2

add mistral + chatml prompts

---

private_gpt/components/llm/llm_component.py

The newer versions of `llama-cpp-python` do not have the parameter `offload_kqv` set to True. Fixing this in privateGPT is pretty straightforward. Instead of installing a lower version of `llama-cpp-python`, adding `"offload_kqv": True` to `model_kwargs` enables KGV offloading, and also significantly boosts GPU performance.

Fix: Adding an LLM param to fix generator producing only "#####" characters

---

fern/docs/pages/manual/vectordb.mdx
poetry.lock
private_gpt/components/vector_store/vector_store_component.py
private_gpt/settings/settings.py
pyproject.toml
settings.yaml

add pgvector as one option to vector store with the following configurations
The available configuration options are:
| Field         | Description                                               |
|---------------|-----------------------------------------------------------|
| **host**      | The server hosting the Postgres database. Default is `localhost` |
| **port**      | The port on which the Postgres database is accessible. Default is `5432` |
| **database**  | The specific database to connect to. Default is `postgres` |
| **user**      | The username for database access. Default is `postgres` |
| **password**  | The password for database access. (Required)            |
| **embed_dim** | The dimensionality of the embedding model (Required)    |
| **schema_name** | The database schema …

feat: support pgvector

---

private_gpt/ui/ui.py

I noticed that every time after restarting PrivateGPT, the output on the screen would vary with similar queries used in "Search Files" mode even though the retrieved 'response' contained the same values that were ordered to the same scores.
After some troubleshooting, it looked like the output from the Source.curate_sources(response) function mixes up the values, which results in sources that are no longer ordered to the reponse scores.
In order to fix this, 'curated_sources' in the 'Source' class is changed from a set to a unique list to ensure that the score order is maintained and the results are consistent.

Maintain score order when curating sources

---

private_gpt/__init__.py
private_gpt/components/llm/llm_component.py
private_gpt/components/vector_store/vector_store_component.py
private_gpt/launcher.py
private_gpt/server/utils/auth.py
private_gpt/settings/settings.py
private_gpt/ui/ui.py
settings-ollama.yaml
settings.yaml
tests/server/utils/test_simple_auth.py

Original PR here:
https://github.com/imartinez/privateGPT/pull/1677
llama-cpp https://llama-cpp-python.readthedocs.io/en/latest/api-reference/
https://docs.llamaindex.ai/en/stable/examples/llm/llama_2_llama_cpp.html#
ollama - https://github.com/run-llama/llama_index/blob/eeb2a60387b8ae1994005ad0eebb672ee02074ff/llama-index-integrations/llms/llama-index-llms-ollama/llama_index/llms/ollama/base.py
No configurable changes. -
openailike - https://docs.llamaindex.ai/en/stable/examples/llm/localai.html#localai
Not sure about the model_kwargs. The value is references for openai, but I could not find documentation on what values were allowed.
openai - https://github.com/run-llama/llama_index/blob/eeb2a60387b8ae1994005ad0eebb672ee02074ff/llama-index-integrations/llms/llama-index-llms-openai/llama_i …

Recreated settings changes - Adds serveral options for llamacpp and ollama

---

private_gpt/__init__.py
tiktoken_cache/.gitignore

Discussed in #1458 , To be able to deploy in offline environment, currently tiktoken_ext package is restricting, which can be cached using the added fixes.

tiktoken cache within repo for offline

---

fern/fern.config.json

privateGPT is on an older version of Fern CLI, which doesn't fully support parsing streaming endpoints defined in OpenAPI, causing an outage on a few pages of the docs under `Contextual Completions`.
Upgrading the CLI and running `fern generate --docs` will fix it.

upgrade fern to 0.17.2 to fix broken docs pages (streaming endpoints)

---

.gitignore
fern/docs/pages/manual/vectordb.mdx
private_gpt/components/vector_store/vector_store_component.py
private_gpt/settings/settings.py
settings-ollama-pg.yaml
settings.yaml

The duel configuration of the **postgres** connection settings for the **nodestore** and the **vector store** has a smell about it.   This PR unifies the connection to a **postgres** database by changing the database mode string from **pgvector** to **postgres**. 
It has an opinionated configuration for the name of the embedding table, and removes it from the configuration.  As the vector table needs to know the embedding model dimension to correctly setup the table, this has been moved into the `embedding:` section.
It was easier to create a PR than trying to explain all this in a discussion forum.

Unify settings for vector and nodestore connections to PostgreSQL

---

private_gpt/server/ingest/ingest_service.py

Improves the speed of launching PrivateGPT's UI when lots of documents are ingested.
Improves the speed of the "list" API.

Faster document listing by directly loading ref docs

---

scripts/utils.py

Improved the **make wipe** command to intelligently detect the database mode and perform the appropriate actions.
A pure file system based profile `setting-fs.yaml`
```
nodestore:
database: simple
vectorstore:
database: chroma
```
Wiping local storage.
```
% PGPT_PROFILES=fs make wipe
15:25:49.072 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'fs']
- Deleted /Users/brettengland/Development/privateGPT/local_data/private_gpt/docstore.json
- Deleted /Users/brettengland/Development/privateGPT/local_data/private_gpt/index_store.json
Wiping /Users/brettengland/Development/privateGPT/local_data/private_gpt/chroma_db...
- Deleted /Users/brettengland/Development/privateGPT/local_data/private_gpt/chroma_db/chroma.sqlite3
```
All data is stored in …

Wipe detects storage type

---

docker-compose.yaml

Make the compose work avoiding Pydantic error not recognizing local as proper mode.

Fixed docker-compose

---

Dockerfile.external
docker-compose.yaml
settings-docker.yaml

Given that we have Ollama as the new recommended setup, I propose to make a modification to the Dockerfile and compose it to make it coherent with the new local setup. I decoupled Ollama from privateGPT, making it a separate microservice.

Fixed Docker version with Ollama

---

private_gpt/components/llm/custom/sagemaker.py

This PR is for a fix for a reported possible **RCE-resulting vulnerability** that I reported on [huntr.com](https://huntr.com/bounties/1d1e8f06-ec45-4b17-ae24-b83a41304c15); Since that `PrivateGPT` used `eval()` instead of `json.loads()` to load the remote-retrieved string into a dictionary, Python-OS-command injections payload can be parsed the response  of `AWS Sagemaker LLM endpoint` can be predicted and manipulated.
In `./private_gpt/components/llm/custom/sagemaker.py` 's `SagemakerLLM` class's `complete()`, we can see a method used to chat with remote `AWS Sagemaker LLM endpoint`
> Amazon SageMaker is a fully managed service that provides every developer and data scientist with the ability to build, train, and deploy machine learning (ML) models quickly. When it comes to large …

Replacing unsafe `eval()` with `json.loads()` to fix known vulnerability.

---

settings.yaml

Enable cors by default but leave all origins, methods and headers so it will work when consuming pgpt directly in the new ts SDK

fix(settings): enable cors by default

---

private_gpt/components/embedding/embedding_component.py
private_gpt/settings/settings.py
settings.yaml

This allows using OpenAI compatible embedding models such as [text-embeddings-inference](https://github.com/huggingface/text-embeddings-inference).
Main changes:
- added embedding_api_base, embedding_api_key, embedding_model to openai settings

Allow parameterizing OpenAI embeddings component (api_base, key, model)

---

fern/docs/pages/manual/settings.mdx

This commit fixes the powershell set up in the documentation in order to ease the setup process.

Fix setup docu

---

fern/docs/pages/installation/concepts.mdx

The link for `/installation` is broken in the "Main Concepts" page.
The correct path would be `./installation` or  maybe `/installation/getting-started/installation`
I am not sure if the `./` would work w/ the docs framework, let me know if that broken link make sure :)

Fix/update concepts.mdx referencing to installation page

---

fern/docs/pages/installation/installation.mdx
poetry.lock
private_gpt/components/embedding/embedding_component.py
private_gpt/components/llm/llm_component.py
private_gpt/settings/settings.py
private_gpt/utils/ollama.py
pyproject.toml
settings.yaml

The aim is to be able to auto-download the ollama models automatically when the server start up. This is an improvement considered within the out-of-the-box changes.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

feat: autopull ollama models

---

private_gpt/ui/ui.py

* Fix when two messages were sent consecutive
* Add `<hr>` before and after of Sources
* Add `favicon`
* Add Zylon logo in footer

fix: gradio bug fixes

---

fern/docs/pages/installation/troubleshooting.mdx
settings-docker.yaml
settings-local.yaml
settings-vllm.yaml
settings.yaml

To reduce the difficulty of switching between different configurations, we will unify all configurations to use [nomic-embed-text](https://huggingface.co/nomic-ai/nomic-embed-text-v1.5 as the default for all models.
This PR

fix: unify embedding models

---

poetry.lock
private_gpt/components/embedding/embedding_component.py
private_gpt/settings/settings.py
pyproject.toml
settings.yaml

https://github.com/zylon-ai/private-gpt/issues/1893#issuecomment-2118629391

fix: nomic embeddings

---

private_gpt/utils/ollama.py

Adding a progress bar when Ollama is downloading models

fix: add progress bar when ollama is pulling models

---

.docker/router.yml
docker-compose.yaml
fern/docs.yml
fern/docs/pages/quickstart/quickstart.mdx

A Docker-compose with multiple profiles has been added to allow running PrivateGPT with Docker on various types of environments.

feat: improve Docker-Compose and quickstart on Docker

---

fern/docs/pages/installation/installation.mdx
fern/docs/pages/installation/troubleshooting.mdx

Add https://github.com/zylon-ai/private-gpt/issues/1979#issuecomment-2183000116 to official documentation

docs: add numpy issue to troubleshooting

---

poetry.lock
pyproject.toml

The current `poetry install` is broken for first installers:
The reason:
- https://github.com/EuDs63/ffmpy is no longer the source repo of ffmpy (archived on 30 July 2024)
No tags available
If you visit https://pypi.org/project/ffmpy/#history, you can see that it points to a new repo: https://github.com/Ch00k/ffmpy
Related Issues:
- https://github.com/zylon-ai/private-gpt/issues/1378
- https://github.com/zylon-ai/private-gpt/issues/1738
- https://github.com/zylon-ai/private-gpt/issues/1795
- https://github.com/zylon-ai/private-gpt/issues/2005
- https://github.com/zylon-ai/private-gpt/issues/2023
- [x ] Bug fix (non-breaking change which fixes an issue)
I ran the command `poetry add ffmpy@0.3.2`, and poetry installed all packages without any problem.
``` 
Updating dependencies
Resolving …
```

Fix: Rectify ffmpy poetry config; update version from 0.3.2 to 0.4.0

---

private_gpt/settings/settings.py
private_gpt/ui/ui.py
settings.yaml

Add default mode to settings files
- [*] New feature (non-breaking change which adds functionality)
- [*] I stared at the code and made sure it makes sense
- [*] Tested functionality within UI
Python: 3.11.9
- [*] I have performed a self-review of my code
- [*] My changes generate no new warnings

Add default mode option to settings

---

private_gpt/components/ingest/ingest_helper.py

When ingesting documents using Postgres some PDF documents could cause `ValueError: A string literal cannot contain NUL (0x00) characters.`. This PR replaces all null bytes before ingesting the documents to make sure this error doesn't happen.
I ran the pgpt server locally using Ollama and Postgers as both the vector and node store. Before the fix document was not injected, and after adding the sanitization the PDF was successfully ingested and stored.
* Hardware: MacbookPro M2Pro
* Toolchain: Ollama, Postgres

Sanitize null bytes before ingestion

---

docker-compose.yaml

Fix for #2066 
When running private gpt with external ollama API, ollama service returns 503 on startup because ollama service (traefik) might not be ready.
- Add healthcheck to ollama service to test for connection to external ollama
- private-gpt-ollama service depends on ollama being service_healthy
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
I did not test the other profiles.
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
Not relevant
I made a configuration change.

Fix 503 when Private GPT calls Ollama API on startup (Docker Compose ollama-api profile)
